[tool.poetry]
name = "stattik-app-search-fuse-bulma"
version = "0.1.0"
description = ""
authors = ["kfields <kurtisfields@gmail.com>"]
packages = [
    { include = "stattik_app_search_fuse_bulma" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
