EOF = 'EOF'
NEWLINE = 'NEWLINE'
SEMICOLON = 'SEMICOLON'
TERMINATOR = 'TERMINATOR'
INDENT = 'INDENT'
DEDENT = 'DEDENT'

LBRACE = 'LBRACE'
RBRACE = 'RBRACE'
LPAREN = 'LPAREN'
RPAREN = 'RPAREN'

BACKTICK = 'BACKTICK'
BANG = 'BANG'