[tool.poetry]
name = "site-markblocks"
version = "0.1.0"
description = ""
authors = ["Kurtis Fields <kurtisfields@gmail.com>"]
packages = [
    { include = "markblocks_site" },
]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
stattik = {path = "../stattik",  develop = true}
stattik-theme-bulma = {path = "../theme-bulma", develop = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
