[tool.poetry]
name = "kfields-site"
version = "0.1.0"
description = ""
authors = ["Kurtis Fields <kurtisfields@gmail.com>"]
packages = [
    { include = "kfields_site" },
]

[tool.poetry.dependencies]
python = "^3.10.0"
stattik = {path = "../stattik",  develop = true}
kfields-site-search = {path = "../kfields-site-search", develop = true}
gql = {extras = ["all"], version = "^3.0.0b0", allow-prereleases = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
